// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3236737665);
}

export function GetBECCatalogueStatus(): $CancellablePromise<$models.BECCatalogueStatus> {
    return $Call.ByID(3210083132);
}

export function ListBECSiteSeries(zone: string | null, subZone: string | null): $CancellablePromise<$models.BECSiteSeries[] | null> {
    return $Call.ByID(1577121349, zone, subZone);
}

export function ListBECSubZones(zone: string | null): $CancellablePromise<$models.BECSubZone[] | null> {
    return $Call.ByID(4185690898, zone);
}

export function ListBECZones(): $CancellablePromise<$models.BECZone[] | null> {
    return $Call.ByID(440057598);
}
