// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CloseService owns one pending native-close handshake for this app instance.
 * Event delivery is advisory: only an exact pending nonce can authorize exit.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CancelClose(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(3536029525, requestID);
}

export function ConfirmClose(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(4146896217, requestID);
}

/**
 * GetPendingCloseRequest permits the frontend to recover an event emitted
 * before its listener mounted. Empty means no pending approval request.
 */
export function GetPendingCloseRequest(): $CancellablePromise<string> {
    return $Call.ByID(3975206515);
}
