// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CanEditMasterBEC(contextID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3701656016, contextID);
}

export function CreatePlot(contextID: string, header: $models.FS882Header): $CancellablePromise<void> {
    return $Call.ByID(3214660085, contextID, header);
}

export function DeleteHumusRecord(contextID: string, plot: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(1969994408, contextID, plot, id);
}

export function DeleteMineralRecord(contextID: string, plot: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(891139180, contextID, plot, id);
}

export function DeleteOtherRecord(contextID: string, plot: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(3941385392, contextID, plot, id);
}

export function DeleteReviewedVegetation(contextID: string, plot: string, request: $models.VegetationDeletionRequest): $CancellablePromise<void> {
    return $Call.ByID(4082659024, contextID, plot, request);
}

export function DeleteVegRecord(contextID: string, plot: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(1524181516, contextID, plot, id);
}

export function GetChildCapabilities(contextID: string, kind: string): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(888099326, contextID, kind);
}

export function GetHeaderCapabilities(contextID: string): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(849894441, contextID);
}

export function GetPlot(contextID: string, plot: string): $CancellablePromise<$models.FS882Header | null> {
    return $Call.ByID(2787654197, contextID, plot);
}

export function ListAuditEntries(contextID: string, plot: string): $CancellablePromise<$models.AuditEntry[] | null> {
    return $Call.ByID(2687960619, contextID, plot);
}

export function ListHumusRecords(contextID: string, plot: string): $CancellablePromise<$models.HumusRecord[] | null> {
    return $Call.ByID(295703714, contextID, plot);
}

export function ListMineralRecords(contextID: string, plot: string): $CancellablePromise<$models.MineralRecord[] | null> {
    return $Call.ByID(4018995846, contextID, plot);
}

export function ListOtherRecords(contextID: string, plot: string): $CancellablePromise<$models.OtherRecord[] | null> {
    return $Call.ByID(989824098, contextID, plot);
}

export function ListSoilSuggestions(contextID: string): $CancellablePromise<$models.SoilSuggestion[] | null> {
    return $Call.ByID(357605878, contextID);
}

export function ListVegRecords(contextID: string, plot: string): $CancellablePromise<$models.VegRecord[] | null> {
    return $Call.ByID(1360779990, contextID, plot);
}

export function ListVegetationAttributeSuggestions(contextID: string): $CancellablePromise<$models.SoilSuggestion[] | null> {
    return $Call.ByID(409085583, contextID);
}

export function ListVegetationSpecies(contextID: string, form: string): $CancellablePromise<$models.VegetationSpeciesOption[] | null> {
    return $Call.ByID(3698188052, contextID, form);
}

export function ListVegetationSpeciesAliases(contextID: string, lookup: $models.VegetationSpeciesLookup): $CancellablePromise<$models.VegetationSpeciesAlias[] | null> {
    return $Call.ByID(4003025460, contextID, lookup);
}

export function ListVegetationSpeciesUsers(contextID: string, lookup: $models.VegetationSpeciesLookup): $CancellablePromise<$models.VegetationSpeciesOption[] | null> {
    return $Call.ByID(3585380524, contextID, lookup);
}

export function RestoreSelectedAuditRecords(contextID: string, plot: string, rowIDs: string[] | null, action: $models.AuditRestoreAction): $CancellablePromise<$models.AuditRestoreResult | null> {
    return $Call.ByID(736886098, contextID, plot, rowIDs, action);
}

export function ReviewVegetationDeletion(contextID: string, plot: string, form: string, id: number): $CancellablePromise<$models.VegetationDeletionReview> {
    return $Call.ByID(2363268444, contextID, plot, form, id);
}

export function SaveHumusRecord(contextID: string, record: $models.HumusRecord): $CancellablePromise<void> {
    return $Call.ByID(2291049458, contextID, record);
}

export function SaveMineralRecord(contextID: string, record: $models.MineralRecord): $CancellablePromise<void> {
    return $Call.ByID(2868675354, contextID, record);
}

export function SaveOtherRecord(contextID: string, record: $models.OtherRecord): $CancellablePromise<void> {
    return $Call.ByID(638265830, contextID, record);
}

export function SaveVegRecord(contextID: string, record: $models.VegRecord): $CancellablePromise<void> {
    return $Call.ByID(2006819882, contextID, record);
}

export function SetAuditRestoreSelection(contextID: string, plot: string, rowIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2095651677, contextID, plot, rowIDs);
}

export function SwitchContext(expectedID: string, requested: $models.ContextSelection): $CancellablePromise<$models.ProjectState> {
    return $Call.ByID(1469329417, expectedID, requested);
}

export function UpdateCollectedRecords(contextID: string, plot: string, updates: $models.CollectedRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(3289076996, contextID, plot, updates);
}

export function UpdateHeightRecords(contextID: string, plot: string, updates: $models.HeightRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(1221733762, contextID, plot, updates);
}

export function UpdateHumusRecord(contextID: string, record: $models.HumusRecord): $CancellablePromise<void> {
    return $Call.ByID(4069893094, contextID, record);
}

export function UpdateMineralRecord(contextID: string, record: $models.MineralRecord): $CancellablePromise<void> {
    return $Call.ByID(1709012342, contextID, record);
}

export function UpdateOtherRecord(contextID: string, record: $models.OtherRecord): $CancellablePromise<void> {
    return $Call.ByID(3386625786, contextID, record);
}

export function UpdateOtherRecords(contextID: string, plot: string, updates: $models.OtherRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(1309024683, contextID, plot, updates);
}

export function UpdatePlot(contextID: string, header: $models.FS882Header): $CancellablePromise<void> {
    return $Call.ByID(3840380656, contextID, header);
}

export function UpdateSoilRecords(contextID: string, plot: string, updates: $models.SoilRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(4096973070, contextID, plot, updates);
}

export function UpdateVegRecord(contextID: string, record: $models.VegRecord): $CancellablePromise<void> {
    return $Call.ByID(1523295806, contextID, record);
}

export function UpdateVegetationAttributes(contextID: string, plot: string, updates: $models.VegetationAttributeUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(4158838458, contextID, plot, updates);
}

export function UpdateVegetationNumbers(contextID: string, plot: string, updates: $models.VegetationNumberUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(3656385183, contextID, plot, updates);
}

export function UpdateVegetationSpecies(contextID: string, plot: string, updates: $models.VegetationSpeciesUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(2708281787, contextID, plot, updates);
}
