// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Conversion is independent of preferences and never edits either plot axis.
 */
export function ConvertCoordinate(axis: string, mode: $models.CoordinateMode, parts: $models.CoordinateParts): $CancellablePromise<number | null> {
    return $Call.ByID(1818759384, axis, mode, parts);
}

export function DecomposeCoordinate(value: number | null, mode: $models.CoordinateMode): $CancellablePromise<$models.CoordinateParts> {
    return $Call.ByID(2015006346, value, mode);
}

export function GetCoordinateMode(): $CancellablePromise<$models.CoordinateMode> {
    return $Call.ByID(1144541844);
}

export function SetCoordinateMode(mode: $models.CoordinateMode): $CancellablePromise<void> {
    return $Call.ByID(3367346984, mode);
}
