// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetGoogleEarthDescriptionFields(contextID: string): $CancellablePromise<$models.GoogleEarthDescriptionFields | null> {
    return $Call.ByID(4226455080, contextID);
}

export function GetGoogleEarthReview(contextID: string, requestJSON: string): $CancellablePromise<$models.GoogleEarthReview | null> {
    return $Call.ByID(1856591641, contextID, requestJSON);
}
