// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetGoogleEarthPreferences(contextID: string): $CancellablePromise<$models.GoogleEarthPreferencesReview | null> {
    return $Call.ByID(260398073, contextID);
}

/**
 * Save always returns a typed receipt, including post-commit failures. An RPC error
 * would discard the committed bit and make an unsafe replay appear appropriate.
 */
export function SaveGoogleEarthPreferences(contextID: string, requestJSON: string): $CancellablePromise<$models.GoogleEarthPreferencesOutcome | null> {
    return $Call.ByID(1153522380, contextID, requestJSON);
}
