// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportReviewedGoogleEarthKML(contextID: string, requestJSON: string): $CancellablePromise<$models.GoogleEarthKMLExportOutcome | null> {
    return $Call.ByID(1351551664, contextID, requestJSON);
}

export function GetGoogleEarthKMLExportReview(contextID: string, requestJSON: string): $CancellablePromise<$models.GoogleEarthKMLExportReview | null> {
    return $Call.ByID(528192001, contextID, requestJSON);
}
