// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLongEnvironmentPreferences(contextID: string): $CancellablePromise<$models.LongEnvironmentPreferencesReview | null> {
    return $Call.ByID(2006205533, contextID);
}

/**
 * Keep the committed receipt outside callbacks: post-commit cancellation must not
 * become an RPC error which loses the irreversible result.
 */
export function SaveLongEnvironmentPreferences(contextID: string, requestJSON: string): $CancellablePromise<$models.LongEnvironmentPreferencesOutcome | null> {
    return $Call.ByID(167306232, contextID, requestJSON);
}
