// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HierarchyInfo {
    "name": string;
    "file": string;
    "version": string;
    "compatible": boolean;
}

export interface HierarchyNode {
    "id": number;
    "name": string | null;
    "parent": number | null;
    "level": number | null;
}

export interface PlotPage {
    "total": number;
    "plots": PlotSummary[] | null;
}

export interface PlotSummary {
    "plotNumber": string;
    "fieldNumber": string | null;
    "plotRepresenting": string | null;
    "zone": string | null;
    "subZone": string | null;
    "siteSeries": string | null;
}

export interface ProjectDiagnostic {
    "file": string;
    "message": string;
}

export interface ProjectInfo {
    "name": string;
    "file": string;
    "version": string;
    "compatible": boolean;
}

export interface ProjectState {
    "activeProject": string;
    "activeSU": string;
    "activeHierarchy": string;
    "hierarchyFile": string;
    "projects": ProjectInfo[] | null;
    "sus": SUInfo[] | null;
    "hierarchies": HierarchyInfo[] | null;
    "diagnostics": ProjectDiagnostic[] | null;
}

export interface SUInfo {
    "name": string;
    "kind": string;
    "compatible": boolean;
}
