// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuditEntry represents a record in <Project>_Audit.
 */
export interface AuditEntry {
    "rowId": string;
    "project": string;
    "user": string;
    "plotNumber": string;
    "table": string;
    "editField": string;
    "editWhen": string;
    "beforeEdit": string | null;
    "afterEdit": string | null;
    "restore": boolean;
    "flag": boolean;
    "id": number | null;
}

export enum AuditRestoreAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuditRestoreCancel = "cancel",
    AuditRestoreRetain = "retain",
    AuditRestorePrune = "prune",
};

export interface AuditRestoreResult {
    "cancelled": boolean;
    "restoredRows": number;
    "prunedAuditRows": number;

    /**
     * Compatibility only; field restoration never deletes Veg rows.
     */
    "cleanedVegRows": number;
}

export interface BECCatalogueStatus {
    "version": number;
    "zoneRows": number;
    "siteSeriesRows": number;
    "duplicateKeys": number;
    "unselectableRows": number;
    "sourceSha256": string;
    "snapshotSha256": string;
}

export interface BECSiteSeries {
    "rowId": string;
    "sourceId": string | null;
    "ssCode": string | null;
    "name": string | null;
    "region": string | null;
    "zone": string | null;
    "subZone": string | null;
    "baseSubZone": string | null;
    "variant": string | null;
    "phase": string | null;
    "siteSeries": string | null;
    "siteSeriesPhase": string | null;
    "variation": string | null;
    "seral": string | null;
    "description": string | null;
    "plantAssociation": string | null;
    "comments": string | null;
    "referenceId": number | null;
    "addedDate": string | null;
    "expiredDate": string | null;
    "originalSourceId": string | null;
    "mergedBGC": string | null;
    "suballiance": string | null;
    "alliance": string | null;
    "missingNpeNa": string | null;
    "transferId": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface BECSubZone {
    "rowId": string;
    "zone": string | null;
    "subZone": string | null;
    "zoneDescription": string | null;
    "description": string | null;
}

export interface BECZone {
    "zone": string | null;
    "description": string | null;
}

export interface CollectedRecordUpdate {
    "id": number;
    "expected": string | null;
    "clicks": number;
}

export interface ContextSelection {
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "hierarchy": string;
    "hierarchyPath": string;
}

export enum CoordinateMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CoordinateModeDD = "dd",
    CoordinateModeDM = "dm",
    CoordinateModeDMS = "dms",
};

export interface CoordinateParts {
    "degrees": number | null;
    "minutes": number | null;
    "seconds": number | null;
    "negative": boolean;
}

export interface EnvironmentReport {
    "project": string;
    "su": string;
    "title": string;
    "fields": EnvironmentReportField[] | null;
    "units": EnvironmentReportUnit[] | null;
    "diagnostics": EnvironmentReportDiagnostic[] | null;
}

export interface EnvironmentReportDiagnostic {
    "code": string;
    "unit": string | null;
    "plotNumber": string | null;
    "count": number;
}

export interface EnvironmentReportField {
    "source": string;
    "key": string;
    "label": string;
    "heading": boolean;
}

export interface EnvironmentReportName {
    "rowId": string;
    "value": ProjectMetadataCell;
}

export interface EnvironmentReportPlot {
    "plotNumber": string;
    "status": string;
    "values": ProjectMetadataCell[] | null;
}

export interface EnvironmentReportUnit {
    "code": string;
    "longName": string | null;
    "nameStatus": string;
    "nameCandidates": EnvironmentReportName[] | null;
    "plots": EnvironmentReportPlot[] | null;
}

export interface EnvironmentSiteUnitChange {
    "plotNumber": string;
    "envRowId": string;
    "adminRowId": string;
    "suRowId": string;
    "before": ProjectMetadataCell;
    "after": ProjectMetadataCell;
}

export interface EnvironmentSiteUnitResult {
    "changedRows": number;
    "historyId": string;
}

export interface EnvironmentSiteUnitReview {
    "contextId": string;
    "project": string;
    "su": string;
    "path": string;
    "env": ProjectMetadataTable;
    "admin": ProjectMetadataTable;
    "target": ProjectMetadataTable;
    "changes": EnvironmentSiteUnitChange[] | null;
    "historyHash": string;
}

export interface EnvironmentSiteUnitTransfer {
    "review": EnvironmentSiteUnitReview;
    "confirmed": boolean;
}

export interface EnvironmentWorkbookOutcome {
    "status": string;
    "requestedDestination": string;
    "path": string;
    "sha256": string;
    "errorMessage": string;
}

export interface EnvironmentWorkbookReview {
    "preview": LongEnvironmentPreview;
    "sheets": EnvironmentWorkbookSheet[] | null;
    "approvalHash": string;
    "workbookSHA256": string;
    "bytes": number;
}

export interface EnvironmentWorkbookSheet {
    "unit": string;
    "name": string;
}

/**
 * FS882Header captures the unified Env + Admin join record for a plot.
 */
export interface FS882Header {
    "plotNumber": string;
    "projectId": string | null;
    "surveyor": string | null;
    "date": string | null;
    "fieldNo": string | null;
    "generalLocation": string | null;
    "mapSheet": string | null;
    "utmZone": string | null;
    "easting": number | null;
    "northing": number | null;
    "accuracy": number | null;
    "plotRepresenting": string | null;
    "siteSeries": string | null;
    "transition": string | null;
    "mapUnit": string | null;
    "moistureRegime": string | null;
    "nutrientRegime": string | null;
    "successional": string | null;
    "structuralStage": string | null;
    "standAge": number | null;
    "elevation": number | null;
    "slope": number | null;
    "aspect": number | null;
    "mesoSlopePos": string | null;
    "surfaceShape": string | null;
    "microtopType": string | null;
    "microtopSize": string | null;
    "fieldNotes": string | null;
    "officeNotes": string | null;
    "startDate": number | null;
    "airPhotoNum": string | null;
    "becSiteUnit": string | null;
    "bedrockGeology1": string | null;
    "bedrockGeology2": string | null;
    "bedrockGeology3": string | null;
    "coarseFragLith1": string | null;
    "coarseFragLith2": string | null;
    "coarseFragLith3": string | null;
    "ecosection": string | null;
    "enteredBy": string | null;
    "exposure1": string | null;
    "exposure2": string | null;
    "fsRegionDistrict": string | null;
    "floodingRegimeDur": string | null;
    "floodingRegimeFreq": string | null;
    "geoMorProSubSurf": string | null;
    "geoMorProSurf": string | null;
    "humusForm": string | null;
    "humusFormPhase": string | null;
    "humusThickness": number | null;
    "hydroGeoSubSystem": string | null;
    "hydroGeoSystem": string | null;
    "latitude": number | null;
    "longitude": number | null;
    "photo": string | null;
    "realmClass": string | null;
    "rootRestrictingDepth": number | null;
    "rootRestrictingType": string | null;
    "rootZoneParticleSize": string | null;
    "rootingDepth": number | null;
    "seepageDepth": number | null;
    "siteDisturbance1": string | null;
    "siteDisturbance2": string | null;
    "siteDisturbance3": string | null;
    "sitePlotQuality": string | null;
    "soilClassGroup": string | null;
    "soilClassSubGroup": string | null;
    "soilDrainage": string | null;
    "soilNotes": string | null;
    "soilPlotQuality": string | null;
    "soilSurveyor": string | null;
    "speciesListComplete": boolean | null;
    "strataCoverHerb": number | null;
    "strataCoverMoss": number | null;
    "strataCoverShrub": number | null;
    "strataCoverTree": number | null;
    "subZone": string | null;
    "substrateBedRock": number | null;
    "substrateDecWood": number | null;
    "substrateMineralSoil": number | null;
    "substrateOrganicMatter": number | null;
    "substrateRocks": number | null;
    "substrateWater": number | null;
    "surfaceExpSubSurf": string | null;
    "surfaceExpSurf": string | null;
    "surficialMaterialSubSurf": string | null;
    "surficialMaterialSurf": string | null;
    "terrainTextureSubSurf": string | null;
    "terrainTextureSurf": string | null;
    "updatedFromCards": boolean | null;
    "userSiteUnit": string | null;
    "vegNotes": string | null;
    "vegPlotQuality": string | null;
    "vegSurveyor": string | null;
    "waterSource": string | null;
    "xCoord": number | null;
    "yCoord": number | null;
    "zone": string | null;
    "locked": boolean;
}

export interface GeologyCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface GoogleEarthDescriptionFields {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "envTable": string;
    "fields": ProjectMetadataColumn[] | null;
}

export interface GoogleEarthKMLExportOutcome {
    "status": string;
    "requestedDestination": string;
    "path": string;
    "sha256": string;
    "errorMessage": string;
}

export interface GoogleEarthKMLExportReview {
    "review": GoogleEarthKMLReview;
    "approvalHash": string;
    "kmlSHA256": string;
}

export interface GoogleEarthKMLReview {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "descriptionField": string;
    "title": string;
    "placemarkCount": number;
    "byteCount": number;
    "kml": string;
}

export interface GoogleEarthPreferenceValues {
    "title": string;
    "descriptionField": string;
}

export interface GoogleEarthPreferencesOutcome {
    "contextId": string;
    "changed": boolean;
    "committed": boolean;
    "errorMessage": string;
}

export interface GoogleEarthPreferencesReview {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "values": GoogleEarthPreferenceValues;
}

export interface GoogleEarthReview {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "descriptionField": string;
    "fields": EnvironmentReportField[] | null;
    "offset": number;
    "limit": number;
    "totalRows": number;
    "rows": GoogleEarthReviewRow[] | null;
}

export interface GoogleEarthReviewRow {
    "envRowId": string;
    "membershipRowId": string;
    "plotNumber": ProjectMetadataCell;
    "storedLongitude": ProjectMetadataCell;
    "longitude": ProjectMetadataCell;
    "latitude": ProjectMetadataCell;
    "description": ProjectMetadataCell;
}

/**
 * HeightRecordUpdate patches existing vegetation values; nil explicitly means
 * SQL NULL. Expected contains the same keys, using values returned by SQLite.
 */
export interface HeightRecordUpdate {
    "id": number;
    "values": { [_ in string]?: number | null } | null;
    "expected": { [_ in string]?: number | null } | null;
}

export interface HierarchyInfo {
    "name": string;
    "file": string;
    "version": string;
    "compatible": boolean;
    "path"?: string;
}

export interface HierarchyNode {
    "id": number;
    "name": string | null;
    "parent": number | null;
    "level": number | null;
}

/**
 * HumusRecord represents a soil humus layer entry.
 */
export interface HumusRecord {
    "id": number;
    "plotNumber": string;
    "horizon"?: string | null;
    "upperDepth"?: number | null;
    "lowerDepth"?: number | null;
    "ph"?: number | null;
    "comment"?: string | null;
    "humusStructureDegree": string | null;
    "humusStructureKind": string | null;
    "mycelAbundance": string | null;
    "fecalAbundance": string | null;
    "rootsAbundance": string | null;
    "rootsSize": string | null;
    "vonPost": number | null;
}

export interface LifeformSummaryCatalogueRow {
    "rowId": string;
    "lifeform": number;
    "label": ProjectMetadataCell;
    "definition": ProjectMetadataCell;
    "shortName": ProjectMetadataCell;
}

export interface LifeformSummaryEntry {
    "plotNumber": string;
    "species": string;
    "lifeform": number;
    "cover": number;
    "insertSuRowId": string;
    "speciesRowId": string;
    "projectId": ProjectMetadataCell;
}

export interface LifeformSummaryPreview {
    "contextId": string;
    "projectPath": string;
    "suPath": string;
    "report": LifeformSummaryReport;
}

export interface LifeformSummaryReport {
    "project": string;
    "su": string;
    "querySource": string;
    "ordering": string;
    "memberships": VegetationReportMembership[] | null;
    "entries": LifeformSummaryEntry[] | null;
    "catalogue": LifeformSummaryCatalogueRow[] | null;
    "units": LifeformSummaryUnit[] | null;
}

export interface LifeformSummaryRow {
    "catalogueRowId": string;
    "lifeform": number;
    "plotGroups": number;
    "coverCount": number;
    "presence": number | null;
    "meanCover": number | null;
}

export interface LifeformSummaryUnit {
    "code": ProjectMetadataCell;
    "nPlots": number;
    "suRowIds": string[] | null;
    "uniqueSpecies": number;
    "occurrences": number;
    "rows": LifeformSummaryRow[] | null;
}

export interface ListItem {
    "listName": string;
    "item": string;
    "itemDescription": string;
    "itemOrder"?: number | null;
    "fieldUsedIn"?: string;
}

export interface LongEnvironmentOptions {
    "contextId": string;
    "title": string;
}

export interface LongEnvironmentPreferenceValues {
    "title": string;
}

export interface LongEnvironmentPreferencesOutcome {
    "contextId": string;
    "changed": boolean;
    "committed": boolean;
    "errorMessage": string;
}

export interface LongEnvironmentPreferencesReview {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "values": LongEnvironmentPreferenceValues;
}

export interface LongEnvironmentPreview {
    "contextId": string;
    "projectPath": string;
    "suPath": string;
    "report": EnvironmentReport;
}

export interface LongEnvironmentRequest {
    "title": string;
}

export interface LongVegetationDiagnostic {
    "code": string;
    "identity": string;
    "count": number;
}

export interface LongVegetationOptions {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "settings": LongVegetationSettings;
}

export interface LongVegetationPlot {
    "plotNumber": string;
    "cover": number | null;
}

export interface LongVegetationPreview {
    "contextId": string;
    "projectPath": string;
    "suPath": string;
    "settings": LongVegetationSettings;
    "report": LongVegetationReport;
}

export interface LongVegetationQualityCriterion {
    "minimum": string;
    "includeNull": boolean;
}

export interface LongVegetationQualityOccurrence {
    "membershipId": string;
    "plotNumber": ProjectMetadataCell;
    "siteUnit": ProjectMetadataCell;
    "envRowId": string;
    "adminRowId": string;
    "listRowIds": (string | null)[];
    "values": ProjectMetadataCell[];
}

export interface LongVegetationQualityReference {
    "rowId": string;
    "item": ProjectMetadataCell;
    "listName": ProjectMetadataCell;
    "itemOrder": ProjectMetadataCell;
}

export interface LongVegetationQualitySelection {
    "thresholdRowIds": (string[] | null)[];
    "occurrences": LongVegetationQualityOccurrence[] | null;
    "excludedMembershipIds": string[] | null;
    "references": LongVegetationQualityReference[] | null;
}

export interface LongVegetationQualitySettings {
    "site": LongVegetationQualityCriterion;
    "veg": LongVegetationQualityCriterion;
    "soil": LongVegetationQualityCriterion;
}

export interface LongVegetationReport {
    "project": string;
    "su": string;
    "title": string;
    "units": LongVegetationUnit[] | null;
    "diagnostics": LongVegetationDiagnostic[] | null;
    "quality": LongVegetationQualitySelection | null;
}

export interface LongVegetationRow {
    "layer": ProjectMetadataCell;
    "species": ProjectMetadataCell;
    "englishName": ProjectMetadataCell;
    "matchedName": ProjectMetadataCell;
    "presence": number | null;
    "meanCover": number | null;
    "plots": LongVegetationPlot[] | null;
}

export interface LongVegetationSettings {
    "title": string;
    "grouping": string;
    "average": string;
    "constantSpeciesList": boolean;
    "presenceGreaterThan": number;
    "meanCoverGreaterThan": number;
    "order": string;
    "showEnglishName": boolean;
    "showSpeciesCode": boolean;
    "quality": LongVegetationQualitySettings | null;
}

export interface LongVegetationUnit {
    "code": ProjectMetadataCell;
    "longName": string | null;
    "nameStatus": string;
    "nameCandidates": EnvironmentReportName[] | null;
    "numPlots": number;
    "membershipIds": string[] | null;
    "rows": LongVegetationRow[] | null;
}

/**
 * MineralRecord represents a soil mineral layer entry.
 */
export interface MineralRecord {
    "id": number;
    "plotNumber": string;
    "horizon"?: string | null;
    "upperDepth"?: number | null;
    "lowerDepth"?: number | null;
    "texture"?: string | null;
    "colour"?: string | null;
    "comments"?: string | null;
    "pitDepthLimit": string | null;
    "asp": number | null;
    "percentCoarseFragsGravel": number | null;
    "percentCoarseFragsCobbles": number | null;
    "percentCoarseFragsStones": number | null;
    "percentCoarseFragsTotal": number | null;
    "percentCoarseFragsShape": string | null;
    "rootsAbundance": string | null;
    "rootsSize": string | null;
    "mineralStructureClass": string | null;
    "mineralStructureKind": string | null;
    "mineralFormpH": number | null;
}

export interface OtherFlagUpdate {
    "value": boolean | null;
    "expected": boolean | null;
}

/**
 * OtherRecord represents an auxiliary data item.
 */
export interface OtherRecord {
    "id": number;
    "plotNumber": string;
    "dataName"?: string | null;
    "dataItem"?: string | null;
    "userItem1": string | null;
    "userItem2": string | null;
    "userItem3": string | null;
    "userFlag1": boolean | null;
    "userFlag2": boolean | null;
    "userFlag3": boolean | null;
}

export interface OtherRecordUpdate {
    "id": number;
    "text": { [_ in string]?: OtherTextUpdate } | null;
    "flags": { [_ in string]?: OtherFlagUpdate } | null;
}

export interface OtherTextUpdate {
    "value": string | null;
    "expected": string | null;
}

export interface ParentCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface PersonalSpeciesDefinitionRequest {
    "entered": string;
    "scientificName": string | null;
    "lifeform": number | null;
    "englishName": string | null;
}

export interface PlotLocationReport {
    "project": string;
    "su": string;
    "fields": EnvironmentReportField[] | null;
    "rows": PlotLocationRow[] | null;
}

export interface PlotLocationReview {
    "contextId": string;
    "projectPath": string;
    "suPath": string;
    "report": PlotLocationReport;
}

export interface PlotLocationRow {
    "envRowId": string;
    "adminRowId": string;
    "membershipRowIds": string[] | null;
    "storedLongitude": ProjectMetadataCell;
    "values": ProjectMetadataCell[] | null;
}

export interface PlotPage {
    "total": number;
    "plots": PlotSummary[] | null;
}

export interface PlotProfileFileCreated {
    "source": PlotProfileSource;
    "table": string;
    "ruleCount": number;
}

export interface PlotProfileFileCreation {
    "review": PlotProfileFileReview;
    "name": string;
    "path": string;
    "confirmed": boolean;
}

export interface PlotProfileFileReview {
    "template": ProjectMetadataTable;
    "metadataAbsent": boolean;
}

export interface PlotProfileSource {
    "name": string;
    "path": string;
}

export interface PlotProfileSourceInfo {
    "source": PlotProfileSource;
    "table": string;
    "available": boolean;
    "writable": boolean;
    "reason": string;
}

export interface PlotProfileTableCreation {
    "review": PlotProfileTableReview;
    "name": string;
    "confirmed": boolean;
}

export interface PlotProfileTableReview {
    "template": PlotProfileFileReview;
    "profile": ProjectPlotProfileReview;
}

export interface PlotProfileWriteRequest {
    "review": ProjectPlotProfileReview;
    "enabled": boolean;
    "confirmed": boolean;
}

export interface PlotQualityChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface PlotSummary {
    "plotNumber": string;
    "fieldNumber": string | null;
    "plotRepresenting": string | null;
    "zone": string | null;
    "subZone": string | null;
    "siteSeries": string | null;
}

export interface ProfileSUCreated {
    "name": string;
    "path": string;
    "plotCount": number;
}

export interface ProfileSUCreation {
    "review": ProfileSUReview;
    "name": string;
    "path": string;
    "confirmed": boolean;
}

export interface ProfileSUPlot {
    "plotNumber": string;
    "siteUnit": string | null;
}

export interface ProfileSUProjectCreation {
    "review": ProfileSUProjectReview;
    "name": string;
    "confirmed": boolean;
}

export interface ProfileSUProjectReview {
    "su": ProfileSUReview;
    "project": string;
    "path": string;
    "metadata": ProjectMetadataTable;
}

export interface ProfileSUReview {
    "filter": ProjectPlotProfileFilterRequest;
    "template": ProjectMetadataTable;
    "sourceSU": ProjectMetadataTable | null;
    "descriptions": ProjectMetadataTable | null;
    "plots": ProfileSUPlot[] | null;
}

export interface ProjectDiagnostic {
    "file": string;
    "message": string;
}

export interface ProjectInfo {
    "name": string;
    "file": string;
    "version": string;
    "compatible": boolean;
    "path"?: string;
}

export interface ProjectMetadataCell {
    "storage": string;
    "text": string | null;
    "integer": string | null;
    "real": number | null;
    "blobHex": string | null;
}

export interface ProjectMetadataChange {
    "column": string;
    "value": ProjectMetadataCell;
}

export interface ProjectMetadataColumn {
    "name": string;
    "declaredType": string;
}

export interface ProjectMetadataCreate {
    "plotNumber": string;
    "projectId": string | null;
    "original": ProjectMetadataTable;
}

export interface ProjectMetadataEdit {
    "plotNumber": string;
    "projectId": string | null;
    "id": number;
    "columns": ProjectMetadataColumn[] | null;
    "original": ProjectMetadataRow;
    "changes": ProjectMetadataChange[] | null;
    "standardPopulation": string;
}

export interface ProjectMetadataEditorField {
    "name": string;
    "kind": string;
    "maximum": number;
    "collection": boolean;
    "referenceList": string;
    "referenceColumn": string;
    "limitToList": boolean;
    "options": ProjectMetadataOption[] | null;
}

export interface ProjectMetadataOption {
    "rowId": string;
    "value": string | null;
    "description": string | null;
}

export interface ProjectMetadataRestore {
    "review": ProjectMetadataRestoreReview;
    "action": AuditRestoreAction;
    "confirmed": boolean;
}

export interface ProjectMetadataRestoreEvent {
    "historyId": string;
    "created": string;
    "rowId": string;
    "id": number;
    "fields": string[] | null;
    "restored": boolean;
}

export interface ProjectMetadataRestoreHistory {
    "historyPresent": boolean;
    "events": ProjectMetadataRestoreEvent[] | null;
}

export interface ProjectMetadataRestoreReview {
    "contextId": string;
    "historyId": string;
    "project": string;
    "plotNumber": string;
    "projectId": string | null;
    "id": number;
    "columns": ProjectMetadataColumn[] | null;
    "current": ProjectMetadataRow;
    "restored": ProjectMetadataRow;
    "audits": AuditEntry[] | null;
}

export interface ProjectMetadataReview {
    "project": string;
    "plotNumber": string;
    "projectId": string | null;
    "projectRecords": ProjectMetadataTable;
    "masterTemplates": ProjectMetadataTable;
}

export interface ProjectMetadataRow {
    "rowId": string;
    "cells": ProjectMetadataCell[] | null;
}

export interface ProjectMetadataTable {
    "columns": ProjectMetadataColumn[] | null;
    "rows": ProjectMetadataRow[] | null;
}

export interface ProjectMetadataTemplateCreate {
    "blank": ProjectMetadataCreate;
    "master": ProjectMetadataTable;
    "rowId": string;
    "values": ProjectMetadataChange[] | null;
}

export interface ProjectPlotProfileChoices {
    "envFields": string[] | null;
    "species": ProjectMetadataCell[] | null;
}

export interface ProjectPlotProfileCreation {
    "originalRules": ProjectMetadataTable;
    "values": ProjectMetadataChange[] | null;
}

export interface ProjectPlotProfileDeletion {
    "originalRules": ProjectMetadataTable;
    "rowId": string;
    "confirmed": boolean;
}

export interface ProjectPlotProfileEdit {
    "originalRules": ProjectMetadataTable;
    "drafts": ProjectPlotProfileRuleDraft[] | null;
}

export interface ProjectPlotProfileFilterRequest {
    "input": ProjectPlotProfileRunRequest;
    "preview": ProjectPlotProfileResult;
}

export interface ProjectPlotProfileNavigation {
    "contextId": string;
    "result": ProjectPlotProfileResult;
    "plots": PlotSummary[] | null;
}

export interface ProjectPlotProfileResult {
    "project": string;
    "table": string;
    "su": string;
    "totalPlots": number;
    "plotNumbers": string[] | null;
    "steps": ProjectPlotProfileStep[] | null;
}

export interface ProjectPlotProfileReview {
    "project": string;
    "table": string;
    "rules": ProjectMetadataTable;
    "descriptions": ProjectMetadataTable;
    "source": PlotProfileSourceInfo;
}

export interface ProjectPlotProfileRuleDraft {
    "rowId": string;
    "changes": ProjectMetadataChange[] | null;
}

export interface ProjectPlotProfileRunRequest {
    "originalRules": ProjectMetadataTable;
    "projectLump": ProjectMetadataTable | null;
    "subvarieties": boolean;
}

export interface ProjectPlotProfileStep {
    "rowId": string;
    "order": number;
    "operation": string;
    "plotCount": number;
    "remaining": number;
}

export interface ProjectState {
    "activeProject": string;
    "activeSU": string;
    "activeHierarchy": string;
    "hierarchyFile": string;
    "projects": ProjectInfo[] | null;
    "sus": SUInfo[] | null;
    "hierarchies": HierarchyInfo[] | null;
    "diagnostics": ProjectDiagnostic[] | null;
    "contextId"?: string;
    "projectPath"?: string;
    "suPath"?: string;
    "hierarchyPath"?: string;
    "plotProfile": PlotProfileSourceInfo;
}

export interface ProjectTableCSVReview {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "descriptionMetadataPresent": boolean;
    "manifest": TableCSVManifest;
    "csv": string;
}

export interface RegionCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SIVICoverWriteResult {
    "ChangedCells": number;
    "HistoryID": string;
}

export interface SIVIHeightEdit {
    "rowId": string;
    "form": string;
    "column": string;
    "expected": ProjectMetadataCell;
    "value": ProjectMetadataCell;
}

export interface SIVIHeightWriteResult {
    "ChangedCells": number;
    "HistoryID": string;
}

export interface SIVIParentActionInput {
    "contextId": string;
    "controlId": string;
    "table": string;
    "rowId": string;
    "expected": ProjectMetadataCell;
    "option": number | null;
}

export interface SIVIParentActionSaveResult {
    "ChangedCells": number;
    "HistoryID": string;
    "SourceRefreshRequired": boolean;
}

export interface SIVIParentActionWrite {
    "original": SIVIParentProjection | null;
    "actions": SIVIParentActionInput[] | null;
}

export interface SIVIParentBinding {
    "ControlID": string;
    "Binding": string;
    "Table": string;
    "Column": number;
    "Implicit": boolean;
}

export interface SIVIParentCellEdit {
    "contextId": string;
    "table": string;
    "rowId": string;
    "column": string;
    "expected": ProjectMetadataCell;
    "value": ProjectMetadataCell;
}

export interface SIVIParentDirectWrite {
    "original": SIVIParentProjection | null;
    "scalars": SIVIParentCellEdit[] | null;
    "options": SIVIParentCellEdit[] | null;
    "text": SIVIParentCellEdit[] | null;
    "categorical": SIVIParentCellEdit[] | null;
}

export interface SIVIParentJoinReview {
    "ContextID": string;
    "Project": string;
    "Plot": string;
    "Scope": string;
    "Diagnostic": string;
    "Verified": boolean;
    "EnvRowIDs": string[] | null;
    "AdminRowIDs": string[] | null;
}

export interface SIVIParentProjection {
    "ContextID": string;
    "Project": string;
    "Plot": string;
    "Form": string;
    "Query": string;
    "Membership": string;
    "EnvTable": string;
    "AdminTable": string;
    "EnvColumns": ProjectMetadataColumn[] | null;
    "AdminColumns": ProjectMetadataColumn[] | null;
    "Bindings": SIVIParentBinding[] | null;
    "Rows": SIVIParentRow[] | null;
}

export interface SIVIParentRow {
    "Env": ProjectMetadataRow;
    "Admin": ProjectMetadataRow;
}

export interface SIVIParentSharedReference {
    "column": string;
    "listName": string;
    "required": boolean;
    "source": string;
    "available": boolean;
    "diagnostic": string;
    "definitions": ProjectMetadataTable;
    "choices": SIVIParentSharedReferenceChoice[] | null;
}

export interface SIVIParentSharedReferenceChoice {
    "rowId": string;
    "code": string | null;
    "description": string | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SIVIParentSharedReferences {
    "contextId": string;
    "project": string;
    "plot": string;
    "zone": ProjectMetadataCell;
    "fields": SIVIParentSharedReference[] | null;
}

export interface SIVIParentSharedWrite {
    "original": SIVIParentProjection | null;
    "edits": SIVIParentCellEdit[] | null;
}

export interface SIVIParentWriteResult {
    "ChangedCells": number;
    "HistoryID": string;
}

export interface SIVIProjectAssignmentOriginal {
    "Original": SIVIParentProjection | null;
    "Choices": SIVIProjectChoices | null;
    "AssignmentAvailable": boolean;
    "AssignmentDiagnostic": string;
}

export interface SIVIProjectAssignmentWrite {
    "original": SIVIParentProjection | null;
    "selection": SIVIProjectSelection;
}

export interface SIVIProjectChoices {
    "ContextID": string;
    "Project": string;
    "Source": string;
    "Alias": string;
    "Table": string;
    "SourceOption": number;
    "Choices": ProjectMetadataTable;
}

export interface SIVIProjectSelection {
    "contextId": string;
    "controlId": string;
    "table": string;
    "rowId": string;
    "expected": ProjectMetadataCell;
    "sourceOption": number;
    "metadataAlias": string;
    "metadataTable": string;
    "metadataColumns": ProjectMetadataColumn[] | null;
    "metadataOriginal": ProjectMetadataRow;
}

export interface SIVIVegetationProjection {
    "Form": string;
    "Query": string;
    "Columns": string[] | null;
    "Rows": ProjectMetadataRow[] | null;
}

export interface SUInfo {
    "name": string;
    "kind": string;
    "compatible": boolean;
    "path"?: string;
}

export interface ScopedPlotLookup {
    "plotNumber": string;
}

export interface ScopedPlotLookupResult {
    "contextId": string;
    "plot": PlotSummary;
}

export interface SiteCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SiteUnitEnvironmentChange {
    "plotNumber": string;
    "envRowId": string;
    "adminRowId": string;
    "suRowId": string;
    "field": string;
    "origin": string;
    "before": ProjectMetadataCell;
    "after": ProjectMetadataCell;
}

export interface SiteUnitEnvironmentResult {
    "changedRows": number;
    "changedCells": number;
    "historyId": string;
}

export interface SiteUnitEnvironmentReview {
    "contextId": string;
    "project": string;
    "su": string;
    "path": string;
    "env": ProjectMetadataTable;
    "admin": ProjectMetadataTable;
    "source": ProjectMetadataTable;
    "master": ProjectMetadataTable;
    "personal": ProjectMetadataTable;
    "changes": SiteUnitEnvironmentChange[] | null;
    "historyHash": string;
}

export interface SiteUnitEnvironmentTransfer {
    "review": SiteUnitEnvironmentReview;
    "confirmed": boolean;
}

export interface SiteUnitSummaryField {
    "source": string;
    "key": string;
    "label": string;
    "section": string;
    "kind": string;
}

export interface SiteUnitSummaryMembership {
    "rowId": string;
    "plotNumber": ProjectMetadataCell;
    "siteUnit": ProjectMetadataCell;
    "joinedRows": number;
    "status": string;
}

export interface SiteUnitSummaryOptions {
    "contextId": string;
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "method": number;
    "siteUnitType": number;
}

export interface SiteUnitSummaryPlot {
    "plotNumber": string;
    "suRowId": string;
    "envRowId": string;
    "adminRowId": string;
}

export interface SiteUnitSummaryPreferencesOutcome {
    "contextId": string;
    "changed": boolean;
    "committed": boolean;
    "errorMessage": string;
}

export interface SiteUnitSummaryPreview {
    "contextId": string;
    "projectPath": string;
    "suPath": string;
    "report": SiteUnitSummaryReport;
}

export interface SiteUnitSummaryReport {
    "project": string;
    "su": string;
    "method": number;
    "querySource": string;
    "fields": SiteUnitSummaryField[] | null;
    "units": SiteUnitSummaryUnit[] | null;
    "memberships": SiteUnitSummaryMembership[] | null;
}

export interface SiteUnitSummaryRequest {
    "method": number;
}

export interface SiteUnitSummaryUnit {
    "code": string;
    "longName": string | null;
    "nameStatus": string;
    "nameCandidates": EnvironmentReportName[] | null;
    "plots": SiteUnitSummaryPlot[] | null;
    "values": string[] | null;
}

export interface SoilCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SoilNumberUpdate {
    "value": number | null;
    "expected": number | null;
}

export interface SoilRecordUpdate {
    "kind": string;
    "id": number;
    "text": { [_ in string]?: SoilTextUpdate } | null;
    "numbers": { [_ in string]?: SoilNumberUpdate } | null;
}

export interface SoilSuggestion {
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "item": string | null;
    "itemDescription": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
}

export interface SoilTextUpdate {
    "value": string | null;
    "expected": string | null;
}

export interface SpeciesAttributeCount {
    "field": string;
    "count": number | null;
    "plotOccurrences": number;
    "categories": (number | null)[] | null;
}

export interface SpeciesAttributeDefinition {
    "field": string;
    "label": string;
    "categories": string[] | null;
}

export interface SpeciesAttributeMatch {
    "suRowId": string;
    "vegRowId": string;
    "attributeRowId": string;
    "plotNumber": string;
    "species": string;
    "values": ProjectMetadataCell[] | null;
}

export interface SpeciesAttributeSummaryPreview {
    "contextId": string;
    "projectPath": string;
    "suPath": string;
    "report": SpeciesAttributeSummaryReport;
}

export interface SpeciesAttributeSummaryReport {
    "project": string;
    "su": string;
    "querySource": string;
    "definitions": SpeciesAttributeDefinition[] | null;
    "memberships": VegetationReportMembership[] | null;
    "matches": SpeciesAttributeMatch[] | null;
    "units": SpeciesAttributeUnit[] | null;
}

export interface SpeciesAttributeUnit {
    "code": ProjectMetadataCell;
    "nPlots": number;
    "suRowIds": string[] | null;
    "rows": SpeciesAttributeCount[] | null;
}

export interface SpeciesCodeCheckOption {
    "code": string | null;
    "scientificName": string | null;
    "lifeform": number | null;
    "englishName": string | null;
    "codeType": string | null;
    "source": string;
}

export interface SpeciesCodeCheckReview {
    "project": string;
    "su": string;
    "rows": SpeciesCodeCheckRow[] | null;
}

export interface SpeciesCodeCheckRow {
    "id": number;
    "plotNumber": string;
    "code": string | null;
    "status": string;
}

export interface SpeciesCodeCheckUpdate {
    "id": number;
    "plotNumber": string;
    "expected": string | null;
    "value": string;
}

export interface SpeciesItem {
    "code": string;
    "scientificName": string;
    "englishName": string;
    "lifeform"?: number | null;
    "familyCode"?: string;
    "authority"?: string;
}

export interface StartupState {
    "ready": boolean;
    "message": string;
    "configPath": string;
}

export interface TableCSVArchiveOutcome {
    "status": string;
    "requestedDestination": string;
    "path": string;
    "sha256": string;
    "errorMessage": string;
}

export interface TableCSVArchiveReview {
    "review": ProjectTableCSVReview;
    "approvalHash": string;
    "archiveSHA256": string;
    "byteCount": number;
    "format": string;
    "version": number;
}

export interface TableCSVDescription {
    "rowId": string;
    "value": ProjectMetadataCell;
}

export interface TableCSVManifest {
    "version": number;
    "table": string;
    "columns": ProjectMetadataColumn[] | null;
    "rowIds": string[] | null;
    "storage": (string[] | null)[] | null;
    "descriptions": TableCSVDescription[] | null;
    "sha256": string;
}

/**
 * VegRecord represents a vegetation entry (Layer A-D).
 */
export interface VegRecord {
    "id": number;
    "plotNumber": string;
    "species": string;
    "layer"?: string | null;
    "cover1"?: number | null;
    "cover2"?: number | null;
    "cover3"?: number | null;
    "totalA"?: number | null;
    "cover4"?: number | null;
    "cover5"?: number | null;
    "cover5a"?: number | null;
    "cover5b"?: number | null;
    "cover5c"?: number | null;
    "totalB"?: number | null;
    "cover6"?: number | null;
    "cover7"?: number | null;
    "cover8"?: number | null;
    "cover9"?: number | null;
    "cover10"?: number | null;
    "collected"?: string | null;
    "height1": number | null;
    "height2": number | null;
    "height3": number | null;
    "height4": number | null;
    "height5": number | null;
    "height6": number | null;
    "ll": number | null;
    "af": number | null;
    "dc": number | null;
    "ut": number | null;
    "vi": number | null;
    "pv": number | null;
    "pg": number | null;
    "ffa": number | null;
    "cultural1": number | null;
    "cultural2": number | null;
    "other1": number | null;
    "other2": number | null;
}

export interface VegetationAttributeUpdate {
    "id": number;
    "values": { [_ in string]?: number | null } | null;
    "expected": { [_ in string]?: number | null } | null;
}

export interface VegetationCreationRequest {
    "form": string;
    "species": string;
    "values": { [_ in string]?: number | null } | null;
    "decision"?: string;
    "entered"?: string | null;
    "selected"?: string | null;
}

export interface VegetationDeletionRequest {
    "id": number;
    "form": string;
    "expected": string;
}

export interface VegetationDeletionReview {
    "id": number;
    "form": string;
    "species": string | null;
    "expected": string;
    "columns": string[] | null;
}

export interface VegetationNumberUpdate {
    "id": number;
    "values": { [_ in string]?: number | null } | null;
    "expected": { [_ in string]?: number | null } | null;
    "forms": { [_ in string]?: string } | null;
}

export interface VegetationReportMembership {
    "rowId": string;
    "plotNumber": ProjectMetadataCell;
    "siteUnit": ProjectMetadataCell;
}

export interface VegetationSpeciesAlias {
    "code": string | null;
    "scientificName": string | null;
    "lifeform": number | null;
    "englishName": string | null;
    "codeType": string | null;
    "oldCode": string | null;
}

export interface VegetationSpeciesLookup {
    "code": string;
}

export interface VegetationSpeciesOption {
    "code": string | null;
    "scientificName": string | null;
    "lifeform": number | null;
    "englishName": string | null;
    "codeType": string | null;
}

export interface VegetationSpeciesUpdate {
    "id": number;
    "form": string;
    "expected": string;
    "value": string;
    "decision"?: string;
    "entered"?: string | null;
    "selected"?: string | null;
}

export interface VegetationWorkbookOptions {
    "quickReport": boolean;
    "spaceBetweenGroups": boolean;
    "reportSummary": boolean;
}

export interface VegetationWorkbookOutcome {
    "status": string;
    "requestedDestination": string;
    "path": string;
    "sha256": string;
    "errorMessage": string;
}

export interface VegetationWorkbookReview {
    "preview": LongVegetationPreview;
    "options": VegetationWorkbookOptions;
    "summary": VegetationWorkbookSummary | null;
    "scope": string;
    "createdDate": string;
    "sheets": VegetationWorkbookSheet[] | null;
    "skippedUnits": VegetationWorkbookSkippedUnit[] | null;
    "approvalHash": string;
    "workbookSHA256": string;
    "bytes": number;
}

export interface VegetationWorkbookSheet {
    "unit": ProjectMetadataCell;
    "name": string;
}

export interface VegetationWorkbookSkippedUnit {
    "unit": ProjectMetadataCell;
    "reason": string;
}

export interface VegetationWorkbookSummary {
    "createdDate": string;
    "environmentRows": number;
    "selectedPlotRows": number;
    "speciesVersion": ProjectMetadataCell;
    "versionStatus": string;
    "versionDefinitions": ProjectMetadataTable;
}

export interface WorkingUnitChoice {
    "rowId": string;
    "origin": string;
    "sourceId": string | null;
    "code": string | null;
    "description": string | null;
    "scientificName": string | null;
    "level": number | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface WorkingUnitModeState {
    "mode": string;
    "warning": string | null;
}
