// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuditEntry represents a record in <Project>_Audit.
 */
export interface AuditEntry {
    "rowId": string;
    "project": string;
    "user": string;
    "plotNumber": string;
    "table": string;
    "editField": string;
    "editWhen": string;
    "beforeEdit": string | null;
    "afterEdit": string | null;
    "restore": boolean;
    "flag": boolean;
    "id": number | null;
}

export enum AuditRestoreAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuditRestoreCancel = "cancel",
    AuditRestoreRetain = "retain",
    AuditRestorePrune = "prune",
};

export interface AuditRestoreResult {
    "cancelled": boolean;
    "restoredRows": number;
    "prunedAuditRows": number;

    /**
     * Compatibility only; field restoration never deletes Veg rows.
     */
    "cleanedVegRows": number;
}

export interface BECCatalogueStatus {
    "version": number;
    "zoneRows": number;
    "siteSeriesRows": number;
    "duplicateKeys": number;
    "unselectableRows": number;
    "sourceSha256": string;
    "snapshotSha256": string;
}

export interface BECSiteSeries {
    "rowId": string;
    "sourceId": string | null;
    "ssCode": string | null;
    "name": string | null;
    "region": string | null;
    "zone": string | null;
    "subZone": string | null;
    "baseSubZone": string | null;
    "variant": string | null;
    "phase": string | null;
    "siteSeries": string | null;
    "siteSeriesPhase": string | null;
    "variation": string | null;
    "seral": string | null;
    "description": string | null;
    "plantAssociation": string | null;
    "comments": string | null;
    "referenceId": number | null;
    "addedDate": string | null;
    "expiredDate": string | null;
    "originalSourceId": string | null;
    "mergedBGC": string | null;
    "suballiance": string | null;
    "alliance": string | null;
    "missingNpeNa": string | null;
    "transferId": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface BECSubZone {
    "rowId": string;
    "zone": string | null;
    "subZone": string | null;
    "zoneDescription": string | null;
    "description": string | null;
}

export interface BECZone {
    "zone": string | null;
    "description": string | null;
}

export interface CollectedRecordUpdate {
    "id": number;
    "expected": string | null;
    "clicks": number;
}

export interface ContextSelection {
    "project": string;
    "projectPath": string;
    "su": string;
    "suPath": string;
    "hierarchy": string;
    "hierarchyPath": string;
}

export enum CoordinateMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CoordinateModeDD = "dd",
    CoordinateModeDM = "dm",
    CoordinateModeDMS = "dms",
};

export interface CoordinateParts {
    "degrees": number | null;
    "minutes": number | null;
    "seconds": number | null;
    "negative": boolean;
}

/**
 * FS882Header captures the unified Env + Admin join record for a plot.
 */
export interface FS882Header {
    "plotNumber": string;
    "projectId": string | null;
    "surveyor": string | null;
    "date": string | null;
    "fieldNo": string | null;
    "generalLocation": string | null;
    "mapSheet": string | null;
    "utmZone": string | null;
    "easting": number | null;
    "northing": number | null;
    "accuracy": number | null;
    "plotRepresenting": string | null;
    "siteSeries": string | null;
    "transition": string | null;
    "mapUnit": string | null;
    "moistureRegime": string | null;
    "nutrientRegime": string | null;
    "successional": string | null;
    "structuralStage": string | null;
    "standAge": number | null;
    "elevation": number | null;
    "slope": number | null;
    "aspect": number | null;
    "mesoSlopePos": string | null;
    "surfaceShape": string | null;
    "microtopType": string | null;
    "microtopSize": string | null;
    "fieldNotes": string | null;
    "officeNotes": string | null;
    "startDate": number | null;
    "airPhotoNum": string | null;
    "becSiteUnit": string | null;
    "bedrockGeology1": string | null;
    "bedrockGeology2": string | null;
    "bedrockGeology3": string | null;
    "coarseFragLith1": string | null;
    "coarseFragLith2": string | null;
    "coarseFragLith3": string | null;
    "ecosection": string | null;
    "enteredBy": string | null;
    "exposure1": string | null;
    "exposure2": string | null;
    "fsRegionDistrict": string | null;
    "floodingRegimeDur": string | null;
    "floodingRegimeFreq": string | null;
    "geoMorProSubSurf": string | null;
    "geoMorProSurf": string | null;
    "humusForm": string | null;
    "humusFormPhase": string | null;
    "humusThickness": number | null;
    "hydroGeoSubSystem": string | null;
    "hydroGeoSystem": string | null;
    "latitude": number | null;
    "longitude": number | null;
    "photo": string | null;
    "realmClass": string | null;
    "rootRestrictingDepth": number | null;
    "rootRestrictingType": string | null;
    "rootZoneParticleSize": string | null;
    "rootingDepth": number | null;
    "seepageDepth": number | null;
    "siteDisturbance1": string | null;
    "siteDisturbance2": string | null;
    "siteDisturbance3": string | null;
    "sitePlotQuality": string | null;
    "soilClassGroup": string | null;
    "soilClassSubGroup": string | null;
    "soilDrainage": string | null;
    "soilNotes": string | null;
    "soilPlotQuality": string | null;
    "soilSurveyor": string | null;
    "speciesListComplete": boolean | null;
    "strataCoverHerb": number | null;
    "strataCoverMoss": number | null;
    "strataCoverShrub": number | null;
    "strataCoverTree": number | null;
    "subZone": string | null;
    "substrateBedRock": number | null;
    "substrateDecWood": number | null;
    "substrateMineralSoil": number | null;
    "substrateOrganicMatter": number | null;
    "substrateRocks": number | null;
    "substrateWater": number | null;
    "surfaceExpSubSurf": string | null;
    "surfaceExpSurf": string | null;
    "surficialMaterialSubSurf": string | null;
    "surficialMaterialSurf": string | null;
    "terrainTextureSubSurf": string | null;
    "terrainTextureSurf": string | null;
    "updatedFromCards": boolean | null;
    "userSiteUnit": string | null;
    "vegNotes": string | null;
    "vegPlotQuality": string | null;
    "vegSurveyor": string | null;
    "waterSource": string | null;
    "xCoord": number | null;
    "yCoord": number | null;
    "zone": string | null;
    "locked": boolean;
}

export interface GeologyCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

/**
 * HeightRecordUpdate patches existing vegetation values; nil explicitly means
 * SQL NULL. Expected contains the same keys, using values returned by SQLite.
 */
export interface HeightRecordUpdate {
    "id": number;
    "values": { [_ in string]?: number | null } | null;
    "expected": { [_ in string]?: number | null } | null;
}

export interface HierarchyInfo {
    "name": string;
    "file": string;
    "version": string;
    "compatible": boolean;
    "path"?: string;
}

export interface HierarchyNode {
    "id": number;
    "name": string | null;
    "parent": number | null;
    "level": number | null;
}

/**
 * HumusRecord represents a soil humus layer entry.
 */
export interface HumusRecord {
    "id": number;
    "plotNumber": string;
    "horizon"?: string | null;
    "upperDepth"?: number | null;
    "lowerDepth"?: number | null;
    "ph"?: number | null;
    "comment"?: string | null;
    "humusStructureDegree": string | null;
    "humusStructureKind": string | null;
    "mycelAbundance": string | null;
    "fecalAbundance": string | null;
    "rootsAbundance": string | null;
    "rootsSize": string | null;
    "vonPost": number | null;
}

export interface ListItem {
    "listName": string;
    "item": string;
    "itemDescription": string;
    "itemOrder"?: number | null;
    "fieldUsedIn"?: string;
}

/**
 * MineralRecord represents a soil mineral layer entry.
 */
export interface MineralRecord {
    "id": number;
    "plotNumber": string;
    "horizon"?: string | null;
    "upperDepth"?: number | null;
    "lowerDepth"?: number | null;
    "texture"?: string | null;
    "colour"?: string | null;
    "comments"?: string | null;
    "pitDepthLimit": string | null;
    "asp": number | null;
    "percentCoarseFragsGravel": number | null;
    "percentCoarseFragsCobbles": number | null;
    "percentCoarseFragsStones": number | null;
    "percentCoarseFragsTotal": number | null;
    "percentCoarseFragsShape": string | null;
    "rootsAbundance": string | null;
    "rootsSize": string | null;
    "mineralStructureClass": string | null;
    "mineralStructureKind": string | null;
    "mineralFormpH": number | null;
}

export interface OtherFlagUpdate {
    "value": boolean | null;
    "expected": boolean | null;
}

/**
 * OtherRecord represents an auxiliary data item.
 */
export interface OtherRecord {
    "id": number;
    "plotNumber": string;
    "dataName"?: string | null;
    "dataItem"?: string | null;
    "userItem1": string | null;
    "userItem2": string | null;
    "userItem3": string | null;
    "userFlag1": boolean | null;
    "userFlag2": boolean | null;
    "userFlag3": boolean | null;
}

export interface OtherRecordUpdate {
    "id": number;
    "text": { [_ in string]?: OtherTextUpdate } | null;
    "flags": { [_ in string]?: OtherFlagUpdate } | null;
}

export interface OtherTextUpdate {
    "value": string | null;
    "expected": string | null;
}

export interface ParentCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface PlotPage {
    "total": number;
    "plots": PlotSummary[] | null;
}

export interface PlotQualityChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface PlotSummary {
    "plotNumber": string;
    "fieldNumber": string | null;
    "plotRepresenting": string | null;
    "zone": string | null;
    "subZone": string | null;
    "siteSeries": string | null;
}

export interface ProjectDiagnostic {
    "file": string;
    "message": string;
}

export interface ProjectInfo {
    "name": string;
    "file": string;
    "version": string;
    "compatible": boolean;
    "path"?: string;
}

export interface ProjectState {
    "activeProject": string;
    "activeSU": string;
    "activeHierarchy": string;
    "hierarchyFile": string;
    "projects": ProjectInfo[] | null;
    "sus": SUInfo[] | null;
    "hierarchies": HierarchyInfo[] | null;
    "diagnostics": ProjectDiagnostic[] | null;
    "contextId"?: string;
    "projectPath"?: string;
    "suPath"?: string;
    "hierarchyPath"?: string;
}

export interface RegionCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SUInfo {
    "name": string;
    "kind": string;
    "compatible": boolean;
    "path"?: string;
}

export interface SiteCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SoilCodeChoice {
    "rowId": string;
    "code": string | null;
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "description": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface SoilNumberUpdate {
    "value": number | null;
    "expected": number | null;
}

export interface SoilRecordUpdate {
    "kind": string;
    "id": number;
    "text": { [_ in string]?: SoilTextUpdate } | null;
    "numbers": { [_ in string]?: SoilNumberUpdate } | null;
}

export interface SoilSuggestion {
    "listName": string | null;
    "listFilter": string | null;
    "itemOrder": number | null;
    "item": string | null;
    "itemDescription": string | null;
    "fieldUsedIn": string | null;
    "validateLoops": string | null;
    "validate": boolean | null;
    "note": string | null;
    "flag": boolean | null;
}

export interface SoilTextUpdate {
    "value": string | null;
    "expected": string | null;
}

export interface SpeciesItem {
    "code": string;
    "scientificName": string;
    "englishName": string;
    "lifeform"?: number | null;
    "familyCode"?: string;
    "authority"?: string;
}

export interface StartupState {
    "ready": boolean;
    "message": string;
    "configPath": string;
}

/**
 * VegRecord represents a vegetation entry (Layer A-D).
 */
export interface VegRecord {
    "id": number;
    "plotNumber": string;
    "species": string;
    "layer"?: string | null;
    "cover1"?: number | null;
    "cover2"?: number | null;
    "cover3"?: number | null;
    "totalA"?: number | null;
    "cover4"?: number | null;
    "cover5"?: number | null;
    "cover5a"?: number | null;
    "cover5b"?: number | null;
    "cover5c"?: number | null;
    "totalB"?: number | null;
    "cover6"?: number | null;
    "cover7"?: number | null;
    "cover8"?: number | null;
    "cover9"?: number | null;
    "cover10"?: number | null;
    "collected"?: string | null;
    "height1": number | null;
    "height2": number | null;
    "height3": number | null;
    "height4": number | null;
    "height5": number | null;
    "height6": number | null;
    "ll": number | null;
    "af": number | null;
    "dc": number | null;
    "ut": number | null;
    "vi": number | null;
    "pv": number | null;
    "pg": number | null;
    "ffa": number | null;
    "cultural1": number | null;
    "cultural2": number | null;
    "other1": number | null;
    "other2": number | null;
}

export interface VegetationAttributeUpdate {
    "id": number;
    "values": { [_ in string]?: number | null } | null;
    "expected": { [_ in string]?: number | null } | null;
}

export interface VegetationCreationRequest {
    "form": string;
    "species": string;
    "values": { [_ in string]?: number | null } | null;
}

export interface VegetationDeletionRequest {
    "id": number;
    "form": string;
    "expected": string;
}

export interface VegetationDeletionReview {
    "id": number;
    "form": string;
    "species": string | null;
    "expected": string;
    "columns": string[] | null;
}

export interface VegetationNumberUpdate {
    "id": number;
    "values": { [_ in string]?: number | null } | null;
    "expected": { [_ in string]?: number | null } | null;
    "forms": { [_ in string]?: string } | null;
}

export interface VegetationSpeciesAlias {
    "code": string | null;
    "scientificName": string | null;
    "lifeform": number | null;
    "englishName": string | null;
    "codeType": string | null;
    "oldCode": string | null;
}

export interface VegetationSpeciesLookup {
    "code": string;
}

export interface VegetationSpeciesOption {
    "code": string | null;
    "scientificName": string | null;
    "lifeform": number | null;
    "englishName": string | null;
    "codeType": string | null;
}

export interface VegetationSpeciesUpdate {
    "id": number;
    "form": string;
    "expected": string;
    "value": string;
    "decision"?: string;
    "entered"?: string | null;
    "selected"?: string | null;
}

export interface WorkingUnitChoice {
    "rowId": string;
    "origin": string;
    "sourceId": string | null;
    "code": string | null;
    "description": string | null;
    "scientificName": string | null;
    "level": number | null;
    "selectable": boolean;
    "diagnostic": string;
}

export interface WorkingUnitModeState {
    "mode": string;
    "warning": string | null;
}
