// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2045502736);
}

export function ListChoices(listName: string): $CancellablePromise<$models.ParentCodeChoice[] | null> {
    return $Call.ByID(1950183236, listName);
}

export function ReloadCatalogue(): $CancellablePromise<void> {
    return $Call.ByID(334352106);
}
