// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetImage(contextID: string, plot: string, requestJSON: string): $CancellablePromise<$models.PictureImage | null> {
    return $Call.ByID(433911198, contextID, plot, requestJSON);
}

export function GetMetadata(contextID: string, plot: string): $CancellablePromise<$models.PictureMetadataReview | null> {
    return $Call.ByID(2102712636, contextID, plot);
}
