// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CanEditMasterBEC(): $CancellablePromise<boolean> {
    return $Call.ByID(2650897432);
}

export function CreatePlot(h: $models.FS882Header): $CancellablePromise<void> {
    return $Call.ByID(3262156109, h);
}

/**
 * DeleteHumusRecord deletes a humus row by ID.
 */
export function DeleteHumusRecord(plotNumber: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(2793278320, plotNumber, id);
}

/**
 * DeleteMineralRecord deletes a mineral row by ID.
 */
export function DeleteMineralRecord(plotNumber: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(3688244948, plotNumber, id);
}

/**
 * DeleteOtherRecord deletes an other data row by ID.
 */
export function DeleteOtherRecord(plotNumber: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(2407169624, plotNumber, id);
}

/**
 * DeleteVegRecord deletes a vegetation entry by ID.
 */
export function DeleteVegRecord(plotNumber: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(1235891316, plotNumber, id);
}

/**
 * GetChildCapabilities reports exact DTO property support, without schema alias
 * guessing. Unbound stored columns are not advertised as editable properties.
 */
export function GetChildCapabilities(kind: string): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(2149314918, kind);
}

/**
 * GetHeaderCapabilities returns exact DTO JSON keys, not guessed schema aliases.
 * locked is always false: the Access option is runtime UI state, not stored data.
 */
export function GetHeaderCapabilities(): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(1963600801);
}

/**
 * GetPlot reads supported nullable fields; unsupported properties remain nil/false.
 */
export function GetPlot(plotNumber: string): $CancellablePromise<$models.FS882Header | null> {
    return $Call.ByID(3703581149, plotNumber);
}

/**
 * ListAuditEntries returns the audit trail for a plot.
 */
export function ListAuditEntries(plotNumber: string): $CancellablePromise<$models.AuditEntry[] | null> {
    return $Call.ByID(2252058387, plotNumber);
}

/**
 * ListHumusRecords returns all humus rows for a plot.
 */
export function ListHumusRecords(plotNumber: string): $CancellablePromise<$models.HumusRecord[] | null> {
    return $Call.ByID(452491274, plotNumber);
}

/**
 * ListMineralRecords returns all mineral rows for a plot.
 */
export function ListMineralRecords(plotNumber: string): $CancellablePromise<$models.MineralRecord[] | null> {
    return $Call.ByID(2369187726, plotNumber);
}

/**
 * ListOtherRecords returns all other data rows for a plot.
 */
export function ListOtherRecords(plotNumber: string): $CancellablePromise<$models.OtherRecord[] | null> {
    return $Call.ByID(403560778, plotNumber);
}

/**
 * ListVegRecords returns all vegetation rows for a plot. NULL IDs are unsupported
 * by the numeric DTO and produce an identity error, never a synthetic zero ID.
 */
export function ListVegRecords(plotNumber: string): $CancellablePromise<$models.VegRecord[] | null> {
    return $Call.ByID(1706347262, plotNumber);
}

/**
 * RestoreAuditRecords preserves the legacy API for rows marked Restore.
 */
export function RestoreAuditRecords(plotNumber: string, removeAuditRows: boolean): $CancellablePromise<void> {
    return $Call.ByID(4102052523, plotNumber, removeAuditRows);
}

/**
 * RestoreSelectedAuditRecords performs an explicit selection, independently of
 * persisted Restore flags. Cancellation and an empty selection never mutate data.
 * Unlike Access CleanVegPlot, field restoration never deletes vegetation records.
 */
export function RestoreSelectedAuditRecords(plotNumber: string, rowIDs: string[] | null, action: $models.AuditRestoreAction): $CancellablePromise<$models.AuditRestoreResult | null> {
    return $Call.ByID(3758961050, plotNumber, rowIDs, action);
}

/**
 * SaveHumusRecord inserts or updates a humus row.
 */
export function SaveHumusRecord(r: $models.HumusRecord): $CancellablePromise<void> {
    return $Call.ByID(1698211082, r);
}

/**
 * SaveMineralRecord inserts or updates a mineral row.
 */
export function SaveMineralRecord(r: $models.MineralRecord): $CancellablePromise<void> {
    return $Call.ByID(163860658, r);
}

/**
 * SaveOtherRecord inserts or updates an other data row.
 */
export function SaveOtherRecord(r: $models.OtherRecord): $CancellablePromise<void> {
    return $Call.ByID(1953514910, r);
}

/**
 * SavePlot is a full replacement of supported header values (nil clears SQL
 * NULL), not a patch. Env, Admin and audits commit or roll back together.
 */
export function SavePlot(h: $models.FS882Header): $CancellablePromise<void> {
    return $Call.ByID(1842717460, h);
}

/**
 * SaveVegRecord creates when ID is zero, otherwise replaces an existing row.
 */
export function SaveVegRecord(r: $models.VegRecord): $CancellablePromise<void> {
    return $Call.ByID(598688130, r);
}

/**
 * SetAuditRestoreSelection atomically replaces this plot's stored Restore flags.
 * Empty selection clears flags; foreign, missing, duplicate or unsupported rows
 * fail without altering the existing selection. rowIds are exact decimal strings.
 */
export function SetAuditRestoreSelection(plotNumber: string, rowIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1590209141, plotNumber, rowIDs);
}

export function SetAuditStrength(strength: number): $CancellablePromise<void> {
    return $Call.ByID(1651933844, strength);
}

export function SetCurrentUser(user: string): $CancellablePromise<void> {
    return $Call.ByID(1759884188, user);
}

export function UpdateCollectedRecords(plot: string, updates: $models.CollectedRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(1064168316, plot, updates);
}

/**
 * UpdateHeightRecords atomically patches one plot's existing rows and audits.
 * It neither allocates/reserves IDs nor inserts/deletes vegetation records.
 * Float64 precision is intentionally retained within the physical Single range.
 */
export function UpdateHeightRecords(plotNumber: string, updates: $models.HeightRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(2348721002, plotNumber, updates);
}

/**
 * UpdateHumusRecord replaces one existing plot/ID pair, including imported ID=0.
 */
export function UpdateHumusRecord(r: $models.HumusRecord): $CancellablePromise<void> {
    return $Call.ByID(485944574, r);
}

/**
 * UpdateMineralRecord replaces one existing plot/ID pair, including imported ID=0.
 */
export function UpdateMineralRecord(r: $models.MineralRecord): $CancellablePromise<void> {
    return $Call.ByID(3659086222, r);
}

/**
 * UpdateOtherRecord replaces one existing plot/ID pair, including imported ID=0.
 */
export function UpdateOtherRecord(r: $models.OtherRecord): $CancellablePromise<void> {
    return $Call.ByID(2136503922, r);
}

/**
 * Patch only explicit cells; expected values prevent stale full-row replacement.
 */
export function UpdateOtherRecords(plot: string, updates: $models.OtherRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(2034353043, plot, updates);
}

export function UpdatePlot(h: $models.FS882Header): $CancellablePromise<void> {
    return $Call.ByID(2912839176, h);
}

export function UpdateSoilRecords(plot: string, updates: $models.SoilRecordUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(2904892086, plot, updates);
}

/**
 * UpdateVegRecord replaces one existing plot/ID pair, including imported ID=0.
 */
export function UpdateVegRecord(r: $models.VegRecord): $CancellablePromise<void> {
    return $Call.ByID(944074230, r);
}

export function UpdateVegetationAttributes(plot: string, updates: $models.VegetationAttributeUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(4041328338, plot, updates);
}

export function UpdateVegetationNumbers(plot: string, updates: $models.VegetationNumberUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(2651910999, plot, updates);
}

export function UpdateVegetationSpecies(plot: string, updates: $models.VegetationSpeciesUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(3323664195, plot, updates);
}
