// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetHierarchyNodes(): $CancellablePromise<$models.HierarchyNode[] | null> {
    return $Call.ByID(2663441084);
}

export function GetState(): $CancellablePromise<$models.ProjectState> {
    return $Call.ByID(2479934697);
}

export function ListPlots(offset: number, limit: number): $CancellablePromise<$models.PlotPage> {
    return $Call.ByID(766533060, offset, limit);
}

export function SelectHierarchy(name: string, file: string): $CancellablePromise<$models.ProjectState> {
    return $Call.ByID(2162191363, name, file);
}

export function SelectProject(name: string): $CancellablePromise<$models.ProjectState> {
    return $Call.ByID(1702153605, name);
}

export function SelectSU(name: string): $CancellablePromise<$models.ProjectState> {
    return $Call.ByID(580278708, name);
}
