// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2502314640);
}

/**
 * GetAllLists returns all dropdown items grouped by list name.
 */
export function GetAllLists(): $CancellablePromise<{ [_ in string]?: $models.ListItem[] | null } | null> {
    return $Call.ByID(1288543664);
}

/**
 * GetListItems returns sorted options for a specific VPRO dropdown list.
 */
export function GetListItems(listName: string): $CancellablePromise<$models.ListItem[] | null> {
    return $Call.ByID(2862116020, listName);
}

/**
 * GetSpecies returns full details for a single species by code.
 */
export function GetSpecies(code: string): $CancellablePromise<$models.SpeciesItem | null> {
    return $Call.ByID(3275973542, code);
}

/**
 * SearchSpecies searches the BC master species list by code prefix or name fragment.
 */
export function SearchSpecies(query: string, limit: number): $CancellablePromise<$models.SpeciesItem[] | null> {
    return $Call.ByID(3830064222, query, limit);
}
