// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(313025340);
}

export function ListEcosectionChoices(): $CancellablePromise<$models.RegionCodeChoice[] | null> {
    return $Call.ByID(906069736);
}

export function ListRegionChoices(): $CancellablePromise<$models.RegionCodeChoice[] | null> {
    return $Call.ByID(4202444580);
}

export function ReloadCatalogue(): $CancellablePromise<void> {
    return $Call.ByID(1882880046);
}
