// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSiteUnitSummaryPreferences(contextID: string): $CancellablePromise<$models.SiteUnitSummaryOptions | null> {
    return $Call.ByID(2452818077, contextID);
}

export function SaveSiteUnitSummaryPreferences(contextID: string, requestJSON: string): $CancellablePromise<$models.SiteUnitSummaryPreferencesOutcome | null> {
    return $Call.ByID(1318540848, contextID, requestJSON);
}
