// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(799531877);
}

export function ListExposureChoices(): $CancellablePromise<$models.SiteCodeChoice[] | null> {
    return $Call.ByID(4105394690);
}

export function ListSiteDisturbanceChoices(): $CancellablePromise<$models.SiteCodeChoice[] | null> {
    return $Call.ByID(2718777524);
}

export function ReloadCatalogue(): $CancellablePromise<void> {
    return $Call.ByID(4045756807);
}
