// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportReviewed(contextID: string, requestJSON: string): $CancellablePromise<$models.SiteUnitSummaryWorkbookOutcome | null> {
    return $Call.ByID(2701254041, contextID, requestJSON);
}

export function GetReview(contextID: string, requestJSON: string): $CancellablePromise<$models.SiteUnitSummaryWorkbookReview | null> {
    return $Call.ByID(3507060978, contextID, requestJSON);
}
