// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetOriginal(contextID: string, plot: string, extended: boolean): $CancellablePromise<$models.SIVIVegetationProjection[] | null> {
    return $Call.ByID(478277268, contextID, plot, extended);
}

export function RestoreReviewed(contextID: string, plot: string, historyID: string, action: $models.AuditRestoreAction): $CancellablePromise<$models.AuditRestoreResult | null> {
    return $Call.ByID(4114200924, contextID, plot, historyID, action);
}

export function SaveReviewed(contextID: string, plot: string, extended: boolean, requestJSON: string): $CancellablePromise<$models.SIVICoverWriteResult | null> {
    return $Call.ByID(2340856197, contextID, plot, extended, requestJSON);
}
