// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Registration is intentionally separate from the XL facade: shared storage
 * does not authorize XL callbacks or its whole-header Save.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetOriginal(contextID: string, plot: string): $CancellablePromise<$models.SIVIParentProjection | null> {
    return $Call.ByID(3762076060, contextID, plot);
}

export function Restore(contextID: string, plot: string, historyID: string, action: $models.AuditRestoreAction): $CancellablePromise<$models.AuditRestoreResult | null> {
    return $Call.ByID(3759121201, contextID, plot, historyID, action);
}

export function Save(contextID: string, plot: string, request: $models.SIVIParentSharedWrite): $CancellablePromise<$models.SIVIParentWriteResult | null> {
    return $Call.ByID(2833640232, contextID, plot, request);
}
