// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVICreationResult | null> {
    return $Call.ByID(1706021725, contextID, requestJSON);
}

export function GetReferences(contextID: string, plot: string): $CancellablePromise<$models.SIVISpeciesReferences> {
    return $Call.ByID(1335936917, contextID, plot);
}

export function LookupReceipt(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVICreationResult | null> {
    return $Call.ByID(77623549, contextID, requestJSON);
}
