// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVIDeletionResult | null> {
    return $Call.ByID(4253394033, contextID, requestJSON);
}

export function GetHistory(contextID: string, plot: string): $CancellablePromise<$models.SIVIDeletionHistoryList | null> {
    return $Call.ByID(774794002, contextID, plot);
}

export function GetOriginal(contextID: string, plot: string, form: string, rowID: string): $CancellablePromise<$models.SIVIDeletionOriginal | null> {
    return $Call.ByID(316322585, contextID, plot, form, rowID);
}

export function GetTargets(contextID: string, plot: string): $CancellablePromise<$models.SIVIDeletionTargets | null> {
    return $Call.ByID(2374607520, contextID, plot);
}

export function LookupReceipt(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVIDeletionResult | null> {
    return $Call.ByID(639399692, contextID, requestJSON);
}

export function LookupRestorationReceipt(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVIDeletionRestorationResult | null> {
    return $Call.ByID(2019131172, contextID, requestJSON);
}

export function Restore(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVIDeletionRestorationResult | null> {
    return $Call.ByID(3809343620, contextID, requestJSON);
}

export function ReviewRestoration(contextID: string, plot: string, historyID: string): $CancellablePromise<$models.SIVIDeletionRestorationReview | null> {
    return $Call.ByID(577494506, contextID, plot, historyID);
}
