// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetHistory(contextID: string, plot: string): $CancellablePromise<$models.SIVICreationUndoHistoryList | null> {
    return $Call.ByID(3663205283, contextID, plot);
}

export function LookupReceipt(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVICreationUndoResult | null> {
    return $Call.ByID(1577641423, contextID, requestJSON);
}

export function Review(contextID: string, plot: string, historyID: string): $CancellablePromise<$models.SIVICreationUndoReview | null> {
    return $Call.ByID(532528623, contextID, plot, historyID);
}

export function Undo(contextID: string, requestJSON: string): $CancellablePromise<$models.SIVICreationUndoResult | null> {
    return $Call.ByID(1188767937, contextID, requestJSON);
}
