// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3695232901);
}

export function ListGreatGroupChoices(): $CancellablePromise<$models.SoilCodeChoice[] | null> {
    return $Call.ByID(3407228165);
}

export function ListSubgroupChoices(): $CancellablePromise<$models.SoilCodeChoice[] | null> {
    return $Call.ByID(982071910);
}
