// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportReviewedTableCSVArchive(contextID: string, requestJSON: string): $CancellablePromise<$models.TableCSVArchiveOutcome | null> {
    return $Call.ByID(4052738686, contextID, requestJSON);
}

export function GetTableCSVArchiveReview(contextID: string, requestJSON: string): $CancellablePromise<$models.TableCSVArchiveReview | null> {
    return $Call.ByID(2423456141, contextID, requestJSON);
}
