// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetOriginal(contextID: string, plot: string, form: string): $CancellablePromise<$models.TwoPageEntryReferenceSnapshot | null> {
    return $Call.ByID(1082572041, contextID, plot, form);
}

export function GetReferences(contextID: string, plot: string, form: string, filters: $models.TwoPageEntryReferenceFilters): $CancellablePromise<$models.TwoPageEntryReferenceSnapshot | null> {
    return $Call.ByID(2405591084, contextID, plot, form, filters);
}

export function Restore(contextID: string, plot: string, form: string, historyID: string, action: $models.AuditRestoreAction): $CancellablePromise<$models.AuditRestoreResult | null> {
    return $Call.ByID(1013331188, contextID, plot, form, historyID, action);
}

export function Save(contextID: string, plot: string, form: string, request: $models.TwoPageParentEntryWrite): $CancellablePromise<$models.SIVIParentWriteResult | null> {
    return $Call.ByID(1775065699, contextID, plot, form, request);
}
