// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(448359572);
}

export function GetMasterWorkingUnitChoices(): $CancellablePromise<$models.WorkingUnitChoice[] | null> {
    return $Call.ByID(1209819961);
}

export function GetWorkingUnitChoices(mode: string): $CancellablePromise<$models.WorkingUnitChoice[] | null> {
    return $Call.ByID(2680459999, mode);
}

export function GetWorkingUnitMode(): $CancellablePromise<$models.WorkingUnitModeState> {
    return $Call.ByID(3422967090);
}

export function SetWorkingUnitMode(mode: string): $CancellablePromise<$models.WorkingUnitModeState> {
    return $Call.ByID(4203091686, mode);
}
